### ISSUE TITLE
Integrate breadcrumb, header, footer changes from vets-website

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/veterans-employment-center#337]
Need to update the header, footer, and breadcrumbs with upcoming changes from the vets-website repo. See:

- [x] department-of-veterans-affairs/vets-website#2489 (Moving secretary's link)
- [x] department-of-veterans-affairs/vets-website#2487 (Veteran's crisis line functionality)
- [ ] department-of-veterans-affairs/vets-website#2440 (Home page, 404 changes)
- [x] department-of-veterans-affairs/vets-website#2422 (Breadcrumbs)

**Comment by webinista** [comment]
@crwallace Please close this if the VEC updates are done.

**Comment by ayaleloehr** [comment]
VEC updates merged yesterday and deploying tomorrow.

**Comment by ayaleloehr** [comment]
Also, VEC 404 points to vets-website 404, so those changes are not needed here.
